config/routes.rb
Rails.application.routes.draw do
  resources :recenzes
  root "recenzes#index"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recenze.rb
class Recenze < ApplicationRecord
    validates :name, :description, format: { with: /\A[a-zA-Z-.,_ˇ´: ]*+\z/ ,
        message: "pouze písmena" }, presence: true
    validates :hodnoceni, numericality: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recenzes_controller.rb
class RecenzesController < ApplicationController
  before_action :set_recenze, only: %i[ show edit update destroy ]

  # GET /recenzes or /recenzes.json
  def index
    @recenzes = Recenze.all
  end

  # GET /recenzes/1 or /recenzes/1.json
  def show
  end

  # GET /recenzes/new
  def new
    @recenze = Recenze.new
  end

  # GET /recenzes/1/edit
  def edit
  end

  # POST /recenzes or /recenzes.json
  def create
    @recenze = Recenze.new(recenze_params)

    respond_to do |format|
      if @recenze.save
        format.html { redirect_to recenze_url(@recenze), notice: "Recenze was successfully created." }
        format.json { render :show, status: :created, location: @recenze }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recenze.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recenzes/1 or /recenzes/1.json
  def update
    respond_to do |format|
      if @recenze.update(recenze_params)
        format.html { redirect_to recenze_url(@recenze), notice: "Recenze was successfully updated." }
        format.json { render :show, status: :ok, location: @recenze }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recenze.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recenzes/1 or /recenzes/1.json
  def destroy
    @recenze.destroy

    respond_to do |format|
      format.html { redirect_to recenzes_url, notice: "Recenze was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recenze
      @recenze = Recenze.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recenze_params
      params.require(:recenze).permit(:name, :description, :hodnoceni, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
    
end

app/helpers/recenzes_helper.rb
module RecenzesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

 
  <main>
    <%= yield %>
  </main>
  </body>
</html>

app/views/pages/main.html.erb
<h1><%= @message %></h1>

app/views/partials/_notice.html.erb
<% if notice.present? %>
<p class="notification is-primary"><%= notice %></p>

<% end %>

app/views/recenzes/_form.html.erb
<%= form_with(model: recenze) do |form| %>
<div className="one-movie">
  <% if recenze.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recenze.errors.count, "error") %> prohibited this recenze from being saved:</h2>

      <ul>
        <% recenze.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :hodnoceni, style: "display: block" %>
    <%= form.text_field :hodnoceni %>
  </div>
    

  <div>
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/recenzes/_recenze.html.erb
<div class="one-recenze">
<div id="<%= dom_id recenze %>">
  <p>
    <b>Název filmu:</b>
    <%= recenze.name %>
  </p>

  <p>
    <b>Popis filmu:</b>
    <%= recenze.description%>
  </p>

  <p>
    <b>Hodnocení:</b>
    <%= number_to_percentage  recenze.hodnoceni, precision: 0 %>
  </p>
  <p>
      <%= link_to "Zobrazit recenzi", recenze, class: "button is-link" %>
    </p>
  
</div>
</div>

app/views/recenzes/edit.html.erb
<section class="one-recenze">
<h1>Editace recenze</h1>

<%= render "form", recenze: @recenze %>

<br>

<div>
  <%= link_to "Zobrazit recenzi", @recenze, class: "button is-link" %> 
  <%= link_to "Zpět na recenze", recenzes_path, class: "button is-link" %>
</div>
</section>

app/views/recenzes/index.html.erb
<div class="row">
<div class="all-recenzes">
<header>
<%= render "partials/notice" %>
</header>
<%= link_to "Nová recenze", new_recenze_path, class: "button is-primary" %>

<section id="recenzes" class="row">
  <% @recenzes.each do |recenze|  %>
    <%= render recenze %>
    
   
  <% end %>
</div>
</section>
</div>

app/views/recenzes/new.html.erb
<section class="all-recenzes">
<div className="one-recenze">

<h1>Nová recenze filmu</h1>

<%= render "form", recenze: @recenze %>

<br>

<div>
  <%= link_to "Back to recenzes", recenzes_path, class: "button is-link" %>
</div>
</section>

app/views/recenzes/show.html.erb
<%= render "partials/notice" %>
<section class="all-recenzes">

<h1>Recenze filmu</h1>
<%= render @recenze %>
<footer class="edit-links">
<div>
  <%= link_to "Editovat recenzi", edit_recenze_path(@recenze), class: "button is-link" %> 
  <%= link_to "Zpět na recenze", recenzes_path, class: "button is-link" %>
</div>

  <%= button_to "Smazat recenzi", @recenze, method: :delete, class: "button is-danger", onclick: "return confirm('Opravdu chcete recenzi vymazat?');" %>

</footer>

</section>